"""build tables from model

Revision ID: 707b80235ea7
Revises: 4b58540f3e57
Create Date: 2025-05-13 05:22:54.930410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '707b80235ea7'
down_revision: Union[str, None] = '4b58540f3e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ))
    op.add_column('news', sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'updated_at')
    op.drop_column('news', 'created_at')
    # ### end Alembic commands ###
